import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Separator } from '@/components/ui/separator';
import NavBar from './components/NavBar';
import { ThemeProvider } from '@/providers/ThemeProvider';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html
        lang="en"
        className={cn(inter.className, 'dark')}
        style={{ colorScheme: 'dark' }}
      >
        <body className="p-5">
          <ThemeProvider>
            <NavBar />
            {/* <Separator /> */}
            <main className="flex flex-grow w-full justify-center items-center dark:bg-neutral-950">
              {children}
            </main>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
